// (c) Copyright by Abraxas Informatik AG
// For license information see LICENSE file

using System.Collections.Generic;
using Voting.Stimmregister.Proto.V1.Services.Models;
using FilterDataType = Voting.Stimmregister.Proto.V1.Services.Models.FilterDataType;
using FilterReference = Voting.Stimmregister.Proto.V1.Services.Models.FilterReference;

namespace Voting.Stimmregister.Test.Utils.MockData;

public static class FilterData
{
    public static readonly Dictionary<FilterReference, FilterDataType[]> ValidDataTypesByFilter = new()
    {
        [FilterReference.MunicipalityName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.OfficialName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.FirstName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.OriginalName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.AllianceName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.AliasName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.OtherName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.CallName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressExtensionLine1] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressExtensionLine2] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressStreet] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressHouseNumber] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressPostOfficeBoxText] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressTown] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressLocality] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ContactAddressZipCode] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressExtensionLine1] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressExtensionLine2] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressStreet] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressHouseNumber] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressPostOfficeBoxText] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressTown] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.ResidenceAddressZipCode] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.MoveInMunicipalityName] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.MoveInCantonAbbreviation] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.MoveInComesFrom] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.MoveInCountryNameShort] = new[] { FilterDataType.String, FilterDataType.Select, FilterDataType.Multiselect },
        [FilterReference.Vn] = new[] { FilterDataType.Numeric, FilterDataType.String },
        [FilterReference.MunicipalityId] = new[] { FilterDataType.Numeric },
        [FilterReference.RestrictedVotingAndElectionRightFederation] = new[] { FilterDataType.Boolean },
        [FilterReference.EVoting] = new[] { FilterDataType.Boolean },
        [FilterReference.DateOfBirthAdjusted] = new[] { FilterDataType.Boolean },
        [FilterReference.MoveInUnknown] = new[] { FilterDataType.Boolean },
        [FilterReference.SendVotingCardsToDomainOfInfluenceReturnAddress] = new[] { FilterDataType.Boolean },
        [FilterReference.Sex] = new[] { FilterDataType.Multiselect },
        [FilterReference.Religion] = new[] { FilterDataType.Multiselect },
        [FilterReference.Country] = new[] { FilterDataType.Multiselect, FilterDataType.Select, FilterDataType.String },
        [FilterReference.TypeOfResidence] = new[] { FilterDataType.Select },
        [FilterReference.ResidencePermit] = new[] { FilterDataType.Select, FilterDataType.Multiselect, FilterDataType.String },
        [FilterReference.DateOfBirth] = new[] { FilterDataType.Date },
        [FilterReference.ResidencePermitValidFrom] = new[] { FilterDataType.Date },
        [FilterReference.ResidencePermitValidTill] = new[] { FilterDataType.Date },
        [FilterReference.ResidenceEntryDate] = new[] { FilterDataType.Date },
        [FilterReference.MoveInArrivalDate] = new[] { FilterDataType.Date },
    };

    public static readonly Dictionary<FilterReference, FilterDataType[]> ValidDataTypesByCalculatedFilter = new()
    {
        [FilterReference.Age] = new[] { FilterDataType.Numeric },
        [FilterReference.SwissCitizenship] = new[] { FilterDataType.Select },
        [FilterReference.OriginName17] = new[] { FilterDataType.String },
        [FilterReference.OriginOnCanton17] = new[] { FilterDataType.String },
        [FilterReference.ContactAddressLine17] = new[] { FilterDataType.String },
        [FilterReference.HasValidationErrors] = new[] { FilterDataType.Boolean },
        [FilterReference.PoliticalCircleId] = new[] { FilterDataType.String },
        [FilterReference.TrafficCircleId] = new[] { FilterDataType.String },
        [FilterReference.CatholicCircleId] = new[] { FilterDataType.String },
        [FilterReference.EvangelicCircleId] = new[] { FilterDataType.String },
        [FilterReference.PeopleCircleId] = new[] { FilterDataType.String },
        [FilterReference.ResidentialDistrictCircleId] = new[] { FilterDataType.String },
        [FilterReference.SchoolCircleId] = new[] { FilterDataType.String },
        [FilterReference.PoliticalCircleName] = new[] { FilterDataType.String },
        [FilterReference.TrafficCircleName] = new[] { FilterDataType.String },
        [FilterReference.CatholicCircleName] = new[] { FilterDataType.String },
        [FilterReference.EvangelicCircleName] = new[] { FilterDataType.String },
        [FilterReference.PeopleCircleName] = new[] { FilterDataType.String },
        [FilterReference.ResidentialDistrictCircleName] = new[] { FilterDataType.String },
        [FilterReference.SchoolCircleName] = new[] { FilterDataType.String },
    };

    public static readonly Dictionary<FilterReference, FilterOperator[]> ValidOperatorsByFilter = new()
    {
        [FilterReference.MunicipalityName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.OfficialName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.FirstName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.OriginalName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.AllianceName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.AliasName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.OtherName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.CallName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.OriginName17] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.OriginOnCanton17] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressExtensionLine1] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressExtensionLine2] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressStreet] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressHouseNumber] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressPostOfficeBoxText] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressLine17] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressTown] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressLocality] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ContactAddressZipCode] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressExtensionLine1] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressExtensionLine2] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressStreet] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressHouseNumber] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressPostOfficeBoxText] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressTown] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidenceAddressZipCode] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.MoveInMunicipalityName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.MoveInCantonAbbreviation] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.MoveInComesFrom] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.MoveInCountryNameShort] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.PoliticalCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.PoliticalCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.CatholicCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.CatholicCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.EvangelicCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.EvangelicCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.SchoolCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.SchoolCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.TrafficCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.TrafficCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidentialDistrictCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.ResidentialDistrictCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.PeopleCircleId] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.PeopleCircleName] = new[] { FilterOperator.Contains, FilterOperator.Equals, FilterOperator.StartsWith, FilterOperator.EndsWith },
        [FilterReference.Vn] = new[] { FilterOperator.Equals },
        [FilterReference.MunicipalityId] = new[] { FilterOperator.Equals },
        [FilterReference.RestrictedVotingAndElectionRightFederation] = new[] { FilterOperator.Equals },
        [FilterReference.EVoting] = new[] { FilterOperator.Equals },
        [FilterReference.DateOfBirthAdjusted] = new[] { FilterOperator.Equals },
        [FilterReference.MoveInUnknown] = new[] { FilterOperator.Equals },
        [FilterReference.HasValidationErrors] = new[] { FilterOperator.Equals },
        [FilterReference.SendVotingCardsToDomainOfInfluenceReturnAddress] = new[] { FilterOperator.Equals },
        [FilterReference.TypeOfResidence] = new[] { FilterOperator.Equals },
        [FilterReference.ResidencePermit] = new[] { FilterOperator.Equals },
        [FilterReference.SwissCitizenship] = new[] { FilterOperator.Equals },
        [FilterReference.Sex] = new[] { FilterOperator.Equals, FilterOperator.Contains },
        [FilterReference.Religion] = new[] { FilterOperator.Equals, FilterOperator.Contains },
        [FilterReference.Country] = new[] { FilterOperator.Equals, FilterOperator.Contains },
        [FilterReference.DateOfBirth] = new[] { FilterOperator.Equals, FilterOperator.Less, FilterOperator.LessEqual, FilterOperator.Greater, FilterOperator.GreaterEqual },
        [FilterReference.ResidencePermitValidFrom] = new[] { FilterOperator.Equals, FilterOperator.Less, FilterOperator.LessEqual, FilterOperator.Greater, FilterOperator.GreaterEqual },
        [FilterReference.ResidencePermitValidTill] = new[] { FilterOperator.Equals, FilterOperator.Less, FilterOperator.LessEqual, FilterOperator.Greater, FilterOperator.GreaterEqual },
        [FilterReference.ResidenceEntryDate] = new[] { FilterOperator.Equals, FilterOperator.Less, FilterOperator.LessEqual, FilterOperator.Greater, FilterOperator.GreaterEqual },
        [FilterReference.MoveInArrivalDate] = new[] { FilterOperator.Equals, FilterOperator.Less, FilterOperator.LessEqual, FilterOperator.Greater, FilterOperator.GreaterEqual },
    };
}
