// (c) Copyright by Abraxas Informatik AG
// For license information see LICENSE file

namespace Voting.Stimmregister.Domain.Enums;

/// <summary>
/// The filter field reference options, which reflects the filterable field names of a person enumeration.
/// Default is 'unspecified'.
/// </summary>
public enum FilterReference
{
    Unspecified,
    Vn,
    MunicipalityId,
    RestrictedVotingAndElectionRightFederation,
    Age,
    SwissCitizenship,
    MunicipalityName,
    OfficialName,
    FirstName,
    Religion,
    Country,
    EVoting,
    Sex,
    DateOfBirth,
    DateOfBirthAdjusted,
    OriginalName,
    AllianceName,
    AliasName,
    OtherName,
    CallName,
    TypeOfResidence,
    OriginName17,
    OriginOnCanton17,
    ResidencePermit,
    ResidencePermitValidFrom,
    ResidencePermitValidTill,
    ResidenceEntryDate,
    ContactAddressExtensionLine1,
    ContactAddressExtensionLine2,
    ContactAddressStreet,
    ContactAddressHouseNumber,
    ContactAddressPostOfficeBoxText,
    ContactAddressLine17,
    ContactAddressTown,
    ContactAddressLocality,
    ContactAddressZipCode,
    ResidenceAddressExtensionLine1,
    ResidenceAddressExtensionLine2,
    ResidenceAddressStreet,
    ResidenceAddressHouseNumber,
    ResidenceAddressPostOfficeBoxText,
    ResidenceAddressTown,
    ResidenceAddressZipCode,
    MoveInArrivalDate,
    MoveInMunicipalityName,
    MoveInCantonAbbreviation,
    MoveInComesFrom,
    MoveInCountryNameShort,
    MoveInUnknown,
    PoliticalCircleId,
    PoliticalCircleName,
    CatholicCircleId,
    CatholicCircleName,
    EvangelicCircleId,
    EvangelicCircleName,
    SchoolCircleId,
    SchoolCircleName,
    TrafficCircleId,
    TrafficCircleName,
    ResidentialDistrictCircleId,
    ResidentialDistrictCircleName,
    PeopleCircleId,
    PeopleCircleName,
    HasValidationErrors,
    SendVotingCardsToDomainOfInfluenceReturnAddress,
    IsHouseholder,
    ResidenceBuildingId,
    ResidenceApartmentId,
}
